name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Deck of cards Docker image
      run: |
        docker build . --tag ghcr.io/shunmau/deckofcards:latest
        docker run ghcr.io/shunmau/deckofcards:latest
        docker push ghcr.io/shunmau/deckofcards:latest
